### PR TITLE
Audit Log

### PR DESCRIPTION
**Pull request by vrto**
### Description

This expands our standard logging library with auditing capabilities. The idea is that moving an entry to the "audit log" means just using the tools we have with additional metadata.

For more details, see the following:
- [RFC 732](https://docs.google.com/document/d/12x09FhwKz4hS-r__kPqn8k5pcnhJ_Iy3DHt7p6OKQcY/edit)
- [RFC 734](https://docs.google.com/document/d/1tv1wNxfqtg4qfJ6jhbd9rFMIt1JCEjGEFzvV5j_i-sI/edit#heading=h.trqab8y0kufp)

The new `(Logger).Audit` call is a special flavor of `Info` call that enriches the standard INFO log statement with a few extra fields:

```json
{
  "SeverityText": "INFO",
  "Timestamp": 1662061536700202000,
  "InstrumentationScope": "NewClient.testing-stuff",
  "Caller": "log/auditlog.go:19",
  "Function": "github.com/sourcegraph/log.(*zapAdapter).Audit",
  "Body": "audit action",
  "Resource": {
    "service.name": "frontend",
    "service.version": "0.0.0+dev",
    "service.instance.id": "Michals-MacBook-Pro.local"
  },
  "Attributes": {
    "audit": "true",
    "audit.actor": {
      "actorUID": "\u0001",
      "ip": "127.0.0.1",
      "X-Forwarded-For": "127.0.0.1, 127.0.0.1"
    },
    "audit.action": "GetObject called",
    "audit.entity": "NewClient.testing-stuff"
  }
}
```

We can filter the audit log statements by the presence of `audit` attribute in the `Attributes` map.

Sample usage:

```
	act := actor.FromContext(ctx)
	cli := requestclient.FromContext(ctx)
        logger := c.logger.Scoped("testing-stuff", "structured logging")
	logger.Audit(sglog.Actor{string(act.UID), cli.IP, cli.ForwardedFor}, "GetObject called")
```
### Design

- audit log builds on top of our existing logging, so that we don't need to think twice about using yet another library along our standard logging, and instrumentation libraries
- an audit log entry should read like: "**an actor takes an action on entity**"
  - an actor is the caller
  - an action is any arbitrary human-readable string
  - entity is inferred from the logger scope (which already defines the component)

### Other options considered

I originally thought that it's better to add a new severity level (`AUDIT`), but since our logging library is primarily an adapter for Zap this felt less idiomatic and way hackier.

### Next steps

- transform gitserver access logs to audit calls
- transform graphql request logs to audit calls
- tee security events inserts to audit calls

## Questions
- What's the best way of marking this API is experimental? I reckon the design will change once we start using it more widely ...
- Is inferring the audited entity name by looking at the logger scope good enough? Should we be able to pass it into the `Audit()` call instead?
- Are there any naming conventions for keys in the `Attributes` map?

### CODE REVIEW

**Comment by vrto** [comment]
Tracking https://github.com/sourcegraph/security/issues/157

**Review by bobheadxi — CHANGES_REQUESTED** [review]
Hmm, I'm hesitant to approve an expansion of the already-very-large Logger interface with something specific to the Sourcegraph application. We already have types and middleware and utilities that correspond to things like Actor and forwarded-for metadata in Sourcegraph - why not just introduce a package that exports a function that accepts a logger? For example, one could introduce `internal/audit`:

```go
package audit

import (
	"github.com/sourcegraph/log"

	"github.com/sourcegraph/sourcegraph/internal/actor"
	"github.com/sourcegraph/sourcegraph/internal/requestclient"
)

func Log(logger log.Logger, act *actor.Actor, client *requestclient.Client, action string) {
	logger.Info("audit action",
		log.String("audit.action", action),
		log.Object("audit.actor",
			log.Int32("actorUID", act.UID),
			log.String("ip", client.IP),
			log.String("X-Forwarded-For", client.ForwardedFor)))

}
```

Then callsites could simply be:

```go
audit.Log(logger, actor.FromContext(ctx), requestclient.FromContext(ctx), "my action")
```

Or even better:

```go
audit.Log(ctx, logger, "my action")
```

and read from context for the caller. This function could even return an error if actor, request client are unset, for example.

The only thing I see here that requires this to be an addition to the core logging library is `audit.entity`, which takes the full scope that is currently inaccessible. I would much prefer we just stick to the OpenTelemetry scope - it is always logged, so adding this field would be a duplication - unless there is a very strong case that `audit.entity` _must_ be the key of the field, in which case we might introduce a `(Logger).Scope() string` instead (though I would prefer not to)

**Comment by jhchabran** [comment]
I agree with @bobheadxi on building a new `audit` package rather than extending the Logger interface. It also matches better the flexibility needed while this is still labeled as experimental.

**Comment by vrto** [comment]
@bobheadxi @jhchabran, thanks for the honest feedback!

I'm definitely not too adamant about this choice, and I understand that this might feel like coupling the logging library too tightly to the main app, and I acknowledge that it would be a design tradeoff.

There is one specific motivation that I believe is worth considering; if we have two different things (standard logger calls and a special audit log call), we force the developers to think about their INFO calls. The developer needs to go through the following mental process:
- I want to log an INFO statement
- but should it be a part of the audit log?
- if yes, I must use `audit/log.`
- if no, I muse use `sglog.`

If we only have one `Logger` interface that can do the `Audit()` call, we give the developer better explorability at their hand without the need of having the additional knowledge of audit logging.

It's a tradeoff; I thought it's perhaps worth it, but I wanted to voice the idea before we close this.

I will meanwhile move to build the `internal/audit` package; we can compare the two PRs and pick whichever feels better.

@bobheadxi re: `audit.entity` - you're right that we don't need to copy the same value twice, I'm happy to drop it and just explain it in the doc. OTOH I am wondering if the audited entity can actually refer to the scope. Like if we're changing something like a site config value from a service called Foo, the scope refers to Foo, but the audited entity isn't Foo, but the site config. That makes me think that we might need to pass it in explicitly.

**Comment by jhchabran** [comment]
Thinking out loud here: 

1. I think that for the experimental aspect, we're still better with a different package for the time being, regardless of what's the final decision. 
2. Are we making the assumption that someone will discover the audit API because they got it as a result of the autocompletion on `logger.[]`? I think we could address that perhaps with some inline documentation? I think we could leverage that more, by writing docs centred more around SG devs, rather than just being reference docs. 
3. Having `logger.Audit` clashes semantically, because it's not a logging level per se, which make it confusing to map mentally. It means you'd have to search for both `logger.Info` and `logger.Audit` to find all `INFO` level messages.
    - Idea: what about `log.Audit` instead, on the same model at `log.Error`, which would decorate that logging line with the appropriate auditing data? That would enable to take in an interface to infer the auditing data in the future. Structs that are to get audited could implement that interface. 
      - `log.Audit(action string, subject audit.Auditable) log.Field` for example. Please note that putting it in an audit package would work as well. 
4. Looking again at the data fed to the `Audit` call, I wonder if all of this couldn't be inferred from a `context.Context`

**Comment by vrto** [comment]
@jhchabran, thanks for your thoughts!

1. sounds good; I will open a PR and tag you once ready for comparison!
2. yes, exactly. If the developer sees "Audit" in their autocomplete popup, they might think, "oh wow, I should totally append this to the audit log."
3. great point w/ severity clash 🤔 Interesting idea using `log.Audit` as a `Field.` I think that's essentially what it is, but it makes the caller think about the implementation detail. Perhaps we should use the audit logging field, but I still see value in a higher-level Audit call so that it is straightforward to find.
4. yeah, I think the only exception is the `action` that is basically the description of the audit action.

**Comment by vrto** [comment]
Closing as we prefer https://github.com/sourcegraph/sourcegraph/pull/41345

**Pull request closed without merging**
